-- MySQL Script generated by MySQL Workbench
-- Tue Mar 28 11:06:31 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Yahtzee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Yahtzee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Yahtzee` DEFAULT CHARACTER SET latin1 ;
USE `Yahtzee` ;

-- -----------------------------------------------------
-- Table `Yahtzee`.`Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yahtzee`.`Game` (
  `idGame` INT NOT NULL,
  PRIMARY KEY (`idGame`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Yahtzee`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yahtzee`.`User` (
  `userName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userName`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Yahtzee`.`Game_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yahtzee`.`Game_has_User` (
  `Game_idGame` INT NOT NULL,
  `User_userName` VARCHAR(45) NOT NULL,
  `score` INT NULL,
  INDEX `fk_Game_has_User_User1_idx` (`User_userName` ASC),
  INDEX `fk_Game_has_User_Game_idx` (`Game_idGame` ASC),
  CONSTRAINT `fk_Game_has_User_Game`
    FOREIGN KEY (`Game_idGame`)
    REFERENCES `Yahtzee`.`Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_User_User1`
    FOREIGN KEY (`User_userName`)
    REFERENCES `Yahtzee`.`User` (`userName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
