-- MySQL Script generated by MySQL Workbench
-- Fri Mar 24 12:52:50 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Yahtzee
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Yahtzee
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `Yahtzee` ;

-- -----------------------------------------------------
-- Table `Yahtzee`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yahtzee`.`User` (
  `userName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yahtzee`.`Game_Score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yahtzee`.`Game_Score` (
  `Score` INT NOT NULL,
  `Game` INT NOT NULL,
  PRIMARY KEY (`Score`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Yahtzee`.`User_has_Game_Score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Yahtzee`.`User_has_Game_Score` (
  `User_userName` VARCHAR(45) NOT NULL,
  `Game_Score_Score` INT NOT NULL,
  PRIMARY KEY (`User_userName`, `Game_Score_Score`),
  INDEX `fk_User_has_Game_Score_Game_Score1_idx` (`Game_Score_Score` ASC),
  INDEX `fk_User_has_Game_Score_User_idx` (`User_userName` ASC),
  CONSTRAINT `fk_User_has_Game_Score_User`
    FOREIGN KEY (`User_userName`)
    REFERENCES `Yahtzee`.`User` (`userName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Game_Score_Game_Score1`
    FOREIGN KEY (`Game_Score_Score`)
    REFERENCES `Yahtzee`.`Game_Score` (`Score`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
